module.exports = {
  REQUEST_CUSTOMERS: 'REQUEST_CUSTOMERS',
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  DEPOSIT_MONEY: 'DEPOSIT_MONEY',
  WITHDRAW_MONEY: 'WITHDRAW_MONEY'
};
