export const CUSTOMER_SELECTED = 'CUSTOMER_SELECTED';
export const CUSTOMER_ADDED = 'CUSTOMER_ADDED';
export const ADDRESS_UPDATED = 'ADDRESS_UPDATED';
export const MONEY_DEPOSITED = 'MONEY_DEPOSITED';
export const MONEY_WITHDRAWN = 'MONEY_WITHDRAWN';
